name: CI
on: [push]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:               # use Michal Hrušecký’s image
      image: ghcr.io/michal-h21/make4ht-action:latest

    steps:
      - uses: actions/checkout@v4
      - name: Build HTML with make4ht
        shell: bash          # so the pipes and back-slashes work
        run: |
         set -e
         apt-get update -qq
         apt-get install -y --no-install-recommends \
         wget curl libnet-ssleay-perl libio-socket-ssl-perl \
         xz-utils ghostscript imagemagick texlive-fonts-extra
         tlmgr init-usertree
         tlmgr option repository \
          https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/tlnet-final
         tlmgr install --usermode mathjax-latex-4ht
         tlmgr install --usermode esvect
         make4ht -u -f html5+mathjax -c .github/workflows/split.cfg -d out -jindex 00-main.tex

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
